apiVersion: v1
kind: Service
metadata:
  name: nodejsexpress
  namespace: default
spec:
  type: LoadBalancer
  selector: 
    app: nodejsexpress
  ports:
    - name: http
      port: 80
      targetPort: 3000